In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

file_path = Path("../data/processed/gb_energy_analysis.csv")

df = pd.read_csv(file_path)

print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns)}")
print(df.columns.tolist())

Rows: 105,169
Columns: 41
['startTime', 'datetime_uk', 'settlementDate', 'settlementPeriod', 'date', 'hour', 'minute', 'day_of_week', 'month', 'year', 'is_weekend', 'biomass_mw', 'coal_mw', 'gas_mw', 'hydro_mw', 'nuclear_mw', 'oil_mw', 'other_generation_mw', 'pumped_storage_mw', 'wind_mw', 'total_generation_mw', 'renewable_generation_mw', 'datetime_uk_check', 'demand_mw', 'transmission_system_demand_mw', 'gas_share', 'renewable_share', 'net_demand_mw', 'month_name', 'day_of_week_num', 'season', 'renewable_demand_coverage', 'gas_demand_coverage', 'demand_band', 'demand_band_order', 'is_peak_global', 'is_peak_year', 'total_generation_mwh', 'renewable_generation_mwh', 'gas_generation_mwh', 'datetime_uk_powerbi']

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 105169 entries, 0 to 105168
Data columns (total 41 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   startTime                      105169 non-null  str
 1   datetime_uk                    105169 non-null  str
 2   settlementDate                 105169 non-null  str
 3   settlementPeriod               105169 non-null  int64
 4   date                           105169 non-null  str
 5   hour                           105169 non-null  int64
 6   minute                         105169 non-null  int64
 7   day_of_week                    105169 non-null  str
 8   month                          105169 non-null  int64
 9   year                           105169 non-null  int64
 10  is_weekend                     105169 non-null  bool
 11  biomass_mw                     105169 non-null  int64
 12  coal_mw                        105169 non-null  int64
 13  gas_mw                         105169 non-null  int64
 14  hydro_mw                       105169 non-null  int64
 15  nuclear_mw                     105169 non-null  int64
 16  oil_mw                         105169 non-null  int64
 17  other_generation_mw            105169 non-null  int64
 18  pumped_storage_mw              105169 non-null  int64
 19  wind_mw                        105169 non-null  int64
 20  total_generation_mw            105169 non-null  int64
 21  renewable_generation_mw        105169 non-null  int64
 22  datetime_uk_check              105169 non-null  str
 23  demand_mw                      105169 non-null  int64
 24  transmission_system_demand_mw  105169 non-null  int64
 25  gas_share                      105131 non-null  float64
 26  renewable_share                105131 non-null  float64
 27  net_demand_mw                  105169 non-null  int64
 28  month_name                     105169 non-null  str
 29  day_of_week_num                105169 non-null  int64
 30  season                         105169 non-null  str
 31  renewable_demand_coverage      105169 non-null  float64
 32  gas_demand_coverage            105169 non-null  float64
 33  demand_band                    105169 non-null  str
 34  demand_band_order              105169 non-null  int64
 35  is_peak_global                 105169 non-null  bool
 36  is_peak_year                   105169 non-null  bool
 37  total_generation_mwh           105169 non-null  float64
 38  renewable_generation_mwh       105169 non-null  float64
 39  gas_generation_mwh             105169 non-null  float64
 40  datetime_uk_powerbi            105169 non-null  str
dtypes: bool(3), float64(7), int64(21), str(10)
memory usage: 44.6 MB

In [3]:
df.head()

,startTime,datetime_uk,settlementDate,settlementPeriod,date,hour,minute,day_of_week,month,year,...,renewable_demand_coverage,gas_demand_coverage,demand_band,demand_band_order,is_peak_global,is_peak_year,total_generation_mwh,renewable_generation_mwh,gas_generation_mwh,datetime_uk_powerbi
0,2020-01-01 00:00:00+00:00,2020-01-01 00:00:00+00:00,2020-01-01,1,2020-01-01,0,0,Wednesday,1,2020,...,0.304822,0.300494,Normal,2,False,False,11847.5,4014.5,3957.5,2020-01-01 00:00:00
1,2020-01-01 00:30:00+00:00,2020-01-01 00:30:00+00:00,2020-01-01,2,2020-01-01,0,30,Wednesday,1,2020,...,0.299766,0.312878,Normal,2,False,False,12117.5,4035.0,4211.5,2020-01-01 00:30:00
2,2020-01-01 01:00:00+00:00,2020-01-01 01:00:00+00:00,2020-01-01,3,2020-01-01,1,0,Wednesday,1,2020,...,0.302909,0.302608,Normal,2,False,False,11907.0,4024.0,4020.0,2020-01-01 01:00:00
3,2020-01-01 01:30:00+00:00,2020-01-01 01:30:00+00:00,2020-01-01,4,2020-01-01,1,30,Wednesday,1,2020,...,0.301274,0.291295,Low,1,False,False,11492.5,3879.5,3751.0,2020-01-01 01:30:00
4,2020-01-01 02:00:00+00:00,2020-01-01 02:00:00+00:00,2020-01-01,5,2020-01-01,2,0,Wednesday,1,2020,...,0.302812,0.280080,Low,1,False,False,11172.0,3796.5,3511.5,2020-01-01 02:00:00

In [6]:
year_summary = (
    df.groupby("year")
      .agg(
          average_demand_mw=("demand_mw", "mean"),
          peak_demand_mw=("demand_mw", "max"),
          average_gas_mw=("gas_mw", "mean"),
          average_renewable_mw=("renewable_generation_mw", "mean"),
          average_wind_mw=("wind_mw", "mean"),
          average_net_demand_mw=("net_demand_mw", "mean")
      )
      .round(2)
)

year_summary

,average_demand_mw,peak_demand_mw,average_gas_mw,average_renewable_mw,average_wind_mw,average_net_demand_mw
year,,,,,,
2020,27153.21,45986,10827.93,8763.49,6225.14,18389.72
2021,28341.06,46433,12263.89,8128.77,5589.81,20212.30
2022,26620.77,46147,12713.51,9123.14,7035.86,17497.64
2023,26052.34,44109,9906.86,9132.64,7236.95,16919.70
2024,26286.76,45202,8285.84,10021.56,7472.90,16265.21
2025,26158.07,45924,8831.29,10497.45,7839.55,15660.62

In [5]:
print(df.columns.tolist())

['startTime', 'datetime_uk', 'settlementDate', 'settlementPeriod', 'date', 'hour', 'minute', 'day_of_week', 'month', 'year', 'is_weekend', 'biomass_mw', 'coal_mw', 'gas_mw', 'hydro_mw', 'nuclear_mw', 'oil_mw', 'other_generation_mw', 'pumped_storage_mw', 'wind_mw', 'total_generation_mw', 'renewable_generation_mw', 'datetime_uk_check', 'demand_mw', 'transmission_system_demand_mw', 'gas_share', 'renewable_share', 'net_demand_mw', 'month_name', 'day_of_week_num', 'season', 'renewable_demand_coverage', 'gas_demand_coverage', 'demand_band', 'demand_band_order', 'is_peak_global', 'is_peak_year', 'total_generation_mwh', 'renewable_generation_mwh', 'gas_generation_mwh', 'datetime_uk_powerbi']

In [7]:
year_summary = (
    df.groupby("year")
      .agg(
          average_demand_mw=("demand_mw", "mean"),
          peak_demand_mw=("demand_mw", "max"),
          average_gas_mw=("gas_mw", "mean"),
          average_renewable_mw=("renewable_generation_mw", "mean"),
          average_wind_mw=("wind_mw", "mean"),
          average_net_demand_mw=("net_demand_mw", "mean")
      )
      .round(2)
)

year_summary

,average_demand_mw,peak_demand_mw,average_gas_mw,average_renewable_mw,average_wind_mw,average_net_demand_mw
year,,,,,,
2020,27153.21,45986,10827.93,8763.49,6225.14,18389.72
2021,28341.06,46433,12263.89,8128.77,5589.81,20212.30
2022,26620.77,46147,12713.51,9123.14,7035.86,17497.64
2023,26052.34,44109,9906.86,9132.64,7236.95,16919.70
2024,26286.76,45202,8285.84,10021.56,7472.90,16265.21
2025,26158.07,45924,8831.29,10497.45,7839.55,15660.62

In [8]:
renewable_share = (
    df.groupby("year")
      .agg(
          renewable_mw=("renewable_generation_mw", "mean"),
          demand_mw=("demand_mw", "mean")
      )
)

renewable_share["renewable_share"] = (
    renewable_share["renewable_mw"] /
    renewable_share["demand_mw"]
)

renewable_share["renewable_share_pct"] = (
    renewable_share["renewable_share"] * 100
)

renewable_share.round(2)

      renewable_mw  demand_mw  renewable_share  renewable_share_pct
year
2020       8763.49   27153.21             0.32                32.27
2021       8128.77   28341.06             0.29                28.68
2022       9123.14   26620.77             0.34                34.27
2023       9132.64   26052.34             0.35                35.05
2024      10021.56   26286.76             0.38                38.12
2025      10497.45   26158.07             0.40                40.13

In [9]:
peak_year = year_summary["peak_demand_mw"].idxmax()
peak_value = year_summary["peak_demand_mw"].max()

print(f"Peak demand year: {peak_year}")
print(f"Peak demand: {peak_value:,.0f} MW")

Peak demand year: 2021
Peak demand: 46,433 MW

In [10]:
hourly_demand = (
    df.groupby("hour")["demand_mw"]
      .mean()
      .sort_values(ascending=False)
)

print("Highest average-demand hours:")
print(hourly_demand.head(5).round(0))

print("\nLowest average-demand hours:")
print(hourly_demand.sort_values().head(5).round(0))

Highest average-demand hours:
hour
18    32890.0
17    32364.0
19    32302.0
20    30919.0
16    30368.0
Name: demand_mw, dtype: float64

Lowest average-demand hours:
hour
4    20126.0
3    20452.0
5    20785.0
2    21086.0
1    21788.0
Name: demand_mw, dtype: float64

In [11]:
net_hourly = (
    df.groupby("hour")["net_demand_mw"]
      .mean()
      .sort_values(ascending=False)
)

print("Highest average net-demand hours:")
print(net_hourly.head(5).round(0))

Highest average net-demand hours:
hour
18    22953.0
17    22511.0
19    22392.0
20    21110.0
16    20733.0
Name: net_demand_mw, dtype: float64